### ISSUE TITLE
unexpected peer on first launch

### ISSUE THREAD

**Issue by masukomi** [automerge/trellis#54]
Launched it for the 1st time
a) there's a document added by Meriweather
b) meriweather is listed as a peer

I _assume_ that this is just some startup data but this also implies that the Meriweather peer can see changes I make, which would be not good. 

refusing to continue with app not knowing who can see my work or why meriweather is showing up as a peer.

<img width="418" alt="trellis" src="https://user-images.githubusercontent.com/2829/69445600-a9f8f080-0d20-11ea-9f05-ca40bba9f6cf.png">

**Comment by pvh** [comment]
You're quite welcome not to use this software, but in case anyone else comes across this issue, I believe (based on the example below) that your username is Meriweather and the change you're seeing is your own.
